apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ok-lion-nodejs 
  janus-idp.io/tekton: ok-lion-nodejs
  backstage.io/kubernetes-id: ok-lion-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok-lion-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  