apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ok-lion-nodejs
  janus-idp.io/tekton: ok-lion-nodejs
  backstage.io/kubernetes-id: ok-lion-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok-lion-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
